services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcg-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tcg_database
    command: ["npm", "run", "dev:hot"] # Use dev command for live development

  mongodb:
    image: mongo:6.0
    container_name: tcg-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
